spring:
  datasource:
    url: ${MYSQL_JDBC_URL:jdbc:mysql://mysql-data:3306/booksDB?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false}
    username: ${MYSQL_USERNAME:user}
    password: ${MYSQL_PASSWORD:pass}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
    hibernate:
      ddl-auto: update
  web:
    resources:
      add-mappings: true
  application:
    name: library-service

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka@discovery-server:8761/eureka

openapi:
  service:
    title: library-service doc
    version: 1.0.0
    url: http://localhost:8080

springdoc:
  api-docs:
    path: /library-service/v3/api-docs
  swagger-ui:
    path: /library-service/swagger-ui.html