---
version: '3.7'
services:

  mysql-data:
    image: mysql:8.0
    container_name: mysql-data
    environment:
      - MYSQL_ROOT_PASSWORD=Viktor1032003
      - MYSQL_DATABASE=booksDB
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - mysqldb_data:/var/lib/mysql
    restart: always

  discovery-server:
    image: viktordiktor/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: always

  api-gateway:
    image: viktordiktor/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
    depends_on:
      - discovery-server
    links:
      - discovery-server
    restart: always

  book-service:
    container_name: book-service
    image: viktordiktor/book-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway
      - mysql-data
    links:
      - discovery-server
      - mysql-data
    restart: always

  library-service:
    container_name: library-service
    image: viktordiktor/library-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway
      - book-service
      - mysql-data
    links:
      - discovery-server
    restart: always


  authentication-service:
    container_name: authentication-service
    image: viktordiktor/authentication-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-server
      - api-gateway
      - mysql-data
      - book-service
    links:
      - discovery-server
      - mysql-data
    restart: always

volumes:
  mysqldb_data:


