---
version: '3.7'
services:

  mysql-data:
    container_name: mysql-data
    image: mysql
    environment:
      MYSQL_DATABASE: booksDB
      MYSQL_ROOT_PASSWORD: Viktor1032003
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./booksDB:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always


  ## Eureka Server
  discovery-server:
    image: viktordiktor/discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    image: viktordiktor/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=TRACE
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka@discovery-server:8761/eureka/
    depends_on:
      - discovery-server
    links:
      - discovery-server

  ## Config-Service Docker Compose Config
  config-service:
    container_name: config-service
    image: viktordiktor/config-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka@discovery-server:8761/eureka/
    depends_on:
      - discovery-server
      - api-gateway
    links:
      - discovery-server

  ## Book-Service Docker Compose Config
  book-service:
    container_name: book-service
    image: viktordiktor/book-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-data:3306/booksDB
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-data:3306/chat?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - DATABASE_HOST_1=mysql-data
      - DATABASE_HOST=localhost
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Viktor1032003
      - DATABASE_NAME=booksDB
      - DATABASE_PORT=3306
    depends_on:
      - discovery-server
      - api-gateway
      - config-service
      - mysql-data
    links:
      - discovery-server
      - mysql-data

  ## Library-Service Docker Compose Config
  library-service:
    container_name: library-service
    image: viktordiktor/library-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-data:3306/booksDB
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    depends_on:
      - discovery-server
      - api-gateway
      - config-service
      - book-service
      - mysql-data
    links:
      - discovery-server


  ## Authentication-Service Docker Compose Config
  authentication-service:
    container_name: authentication-service
    image: viktordiktor/authentication-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-data:3306/booksDB
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-data:3306/chat?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - DATABASE_HOST_1=mysql-data
      - DATABASE_HOST=localhost
      - DATABASE_USER=root
      - DATABASE_PASSWORD=Viktor1032003
      - DATABASE_NAME=booksDB
      - DATABASE_PORT=3306
    depends_on:
      - discovery-server
      - api-gateway
      - config-service
      - mysql-data
    links:
      - discovery-server
      - mysql-data


